#!/bin/sh
# Make a snapshot archive of qnode
cd ~/Projects/Kdevelop
mv util_vcs20[0-9][0-9]-*.txz ~/Archives/snapshots 2>/dev/null
TAR_ARGS="-Jcv
    --exclude-backups
    --exclude=*~
    --exclude=\#*
    --exclude=*.gch
    --exclude=*.txz
    --exclude=util/.seqintra/logs/*

    -f util_vcs$(timestamp).txz util/
" #TAR_ARGS


tar $TAR_ARGS
ls -l util_vcs20[0-9][0-9]-*.txz
cd -
